services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
  db:
    image: postgres:16-alpine
    container_name: postgres_server
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app-network

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]

    restart: on-failure
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge